# Username: imatest
# Password: testtest

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.5.1 #
    container_name: mealie
    restart: always
    ports:
      - "9925:9000" #
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - ./mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: true
      PUID: 1000
      PGID: 1000
      TZ: America/Indianapolis
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      # BASE_URL: https://mealie.yourdomain.com
